env = Environment(CFLAGS=['-g', '-Wall', '-Werror'])

pub_dir = '#../pub'
Export('env pub_dir')

#
# Build all the CFS source code
#
cfs_interposer_lib = SConscript('src/SConscript', variant_dir='obj', duplicate=0)
Export('cfs_interposer_lib')

#
# Build the test cases
#
SConscript('test_src/SConscript', variant_dir='test_obj', duplicate=0)

#
# If the user enters "scons install", we'll install the binaries
# into the top-level pub directory.
#
env.Alias('install', pub_dir)

#
# When we clean the tree, remove the object directories too.
#
Clean('.', ['obj', 'test_obj', pub_dir])
	