#!/bin/bash

#******************************************************************************
# Copyright (c) 2010 Arapiki Solutions Inc.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#    "Peter Smith <psmith@arapiki.com>" - initial API and 
#        implementation and/or initial documentation
#******************************************************************************/ 

#
# A very simple start-up script for the legacy build scanner.
#
java -cp /usr/local/lib/cfs/legacy-build-scanner.jar com.arapiki.disco.scanner.legacy.Main $*
