#******************************************************************************
# Copyright (c) 2010 Arapiki Solutions Inc.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#    "Peter Smith <psmith@arapiki.com>" - initial API and 
#        implementation and/or initial documentation
#*******************************************************************************/ 

#
# SCons build script for the interposer library and cfs executable program.
#

# import the environment (env) from the top-level build script.
Import('*')
	
# build the interposer library.
cfs_interposer_lib = env.SharedLibrary('cfs', 
	['interposer/glibc_interpose.c',
	 'interposer/trace_buffer.c',
	 'interposer/file_name_utils.c'],
	LIBS=['dl'])

# build the cfs executable
cfs_program = env.Program('cfs',
	['cfs_main/cfs.c',
	 'cfs_main/cfs_traverse_source.c',
	 'interposer/trace_buffer.c'],
	LIBS=['z'],
	CPPPATH=['interposer'])
	

# install the executable in <prefix>/bin and the library in <prefix>/lib
env.Install(pub_dir + '/bin', cfs_program)
env.Install(pub_dir + '/lib', cfs_interposer_lib)

# return a reference to the interposer library so we can use it in other parts of the build.
Return('cfs_interposer_lib')
