Import('*')

cfs_program = env.Program('cfs',
	['cfs-main/cfs.c'])
	
cfs_interposer_lib = env.SharedLibrary('cfs', 
	['interposer/syscall_interpose.c'],
	LIBS='dl')

env.Install(pub_dir + '/bin', cfs_program)
env.Install(pub_dir + '/lib', cfs_interposer_lib)

Return('cfs_interposer_lib')
